"""Self-contained HTML patient report for Meso-Regions pipeline outputs.

Generates a single HTML file per patient with slice overlays (reference MRI +
fluid / pleural-region / ECE masks), per-superspel signal-intensity curves, and
the patient-level ECE call. All images are embedded as base64 PNGs — the file
has no external dependencies and no patient data ever leaves the machine.
"""

import base64
import io
from datetime import datetime
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import nibabel as nib
import numpy as np
import pandas as pd

DISCLAIMER = ("Research use only — this report is generated by research "
              "software and must not be used for clinical diagnosis or "
              "treatment decisions.")

PLANES = {"axial": 2, "coronal": 1, "sagittal": 0}


def _fig_to_b64(fig):
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=130, bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode()


def _pick_slice(mask_data, axis):
    """Index of the slice with the largest mask area along `axis`."""
    axes = tuple(i for i in range(3) if i != axis)
    areas = mask_data.sum(axis=axes)
    return int(np.argmax(areas)) if areas.max() > 0 else mask_data.shape[axis] // 2


def _slice2d(data, axis, idx):
    sl = [slice(None)] * 3
    sl[axis] = idx
    return np.rot90(data[tuple(sl)])


def _overlay_figure(image, masks, title_prefix=""):
    """One row of axial/coronal/sagittal overlays. `masks` is
    {label: (data, color)}; slices chosen where the last mask is largest."""
    fig, axes = plt.subplots(1, 3, figsize=(12, 4.2))
    pick_from = list(masks.values())[-1][0] if masks else image
    for ax, (plane, axis) in zip(axes, PLANES.items()):
        idx = _pick_slice(pick_from, axis)
        ax.imshow(_slice2d(image, axis, idx), cmap="gray",
                  interpolation="nearest")
        for label, (data, color) in masks.items():
            m = _slice2d(data, axis, idx)
            overlay = np.zeros((*m.shape, 4))
            overlay[m > 0] = (*matplotlib.colors.to_rgb(color), 0.45)
            ax.imshow(overlay, interpolation="nearest")
        ax.set_title(f"{title_prefix}{plane} (slice {idx})", fontsize=10)
        ax.axis("off")
    handles = [plt.Line2D([0], [0], marker="s", linestyle="", color=c,
                          label=l) for l, (_, c) in masks.items()]
    if handles:
        fig.legend(handles=handles, loc="lower center", ncol=len(handles),
                   frameon=False, fontsize=9)
    return _fig_to_b64(fig)


def _is_ece_positive(t, y, ref_t):
    """Published ECE rule: minimum pre-contrast, peak at or before ref_t,
    monotonically rising before the peak and falling after."""
    y = np.asarray(y, dtype=float)
    if y.max() <= 0:
        return False
    peak = int(np.argmax(y))
    return (int(np.argmin(y)) == 0
            and t[peak] <= ref_t
            and np.all(np.diff(y[:peak + 1]) >= 0)
            and np.all(np.diff(y[peak:]) <= 0))


def _curves_figure(curves_df, ref_t):
    fig, ax = plt.subplots(figsize=(8, 4.5))
    t = [float(c) for c in curves_df.columns]
    n_ece = 0
    for _, row in curves_df.iterrows():
        if _is_ece_positive(t, row.values, ref_t):
            ax.plot(t, row.values, color="crimson", lw=1.4, zorder=2)
            n_ece += 1
        else:
            ax.plot(t, row.values, color="0.75", lw=0.8, zorder=1)
    ax.axvline(ref_t, color="0.4", ls="--", lw=1,
               label=f"{ref_t} s reference")
    ax.plot([], [], color="0.75", label=f"superspels (n={len(curves_df)})")
    ax.plot([], [], color="crimson",
            label=f"satisfy ECE rule (n={n_ece})")
    ax.set_xlabel("Time post-contrast (s)")
    ax.set_ylabel("Mean signal intensity")
    ax.legend(frameon=False, fontsize=9)
    ax.spines[["top", "right"]].set_visible(False)
    return _fig_to_b64(fig), n_ece


def generate_report(image_path, output_path, patient_id="unknown",
                    ece_mask_path=None, fluid_mask_path=None,
                    pleural_mask_path=None, curves_csv=None,
                    ece_curves_csv=None, ref_t=270, method=""):
    """Build the HTML report; returns the output path."""
    img_nii = nib.load(str(image_path))
    image = np.asanyarray(img_nii.dataobj).astype(float)
    voxel_mm3 = float(abs(np.linalg.det(img_nii.affine[:3, :3])))

    masks, stats = {}, []
    for label, path, color in [("pleural fluid", fluid_mask_path, "gold"),
                               ("pleural region", pleural_mask_path, "darkorange"),
                               ("ECE-positive", ece_mask_path, "crimson")]:
        if path:
            data = np.asanyarray(nib.load(str(path)).dataobj)
            data = (data > 0).astype(np.uint8)
            masks[label] = (data, color)
            stats.append((label, int(data.sum()),
                          round(data.sum() * voxel_mm3 / 1000, 1)))

    sections = []
    if masks:
        sections.append(("Overlays",
                         f'<img src="data:image/png;base64,'
                         f'{_overlay_figure(image, masks)}"/>'))

    n_ece = None
    if ece_curves_csv and not curves_csv:
        curves_csv = ece_curves_csv
    if curves_csv:
        curves = pd.read_csv(curves_csv)
        b64, n_ece = _curves_figure(curves, ref_t)
        sections.append(("Signal-intensity curves",
                         f'<img src="data:image/png;base64,{b64}"/>'))

    ece_present = (n_ece or 0) > 0 or (
        "ECE-positive" in masks and masks["ECE-positive"][0].sum() > 0)
    call = ("ECE-POSITIVE — malignancy suspected by the automated rule"
            if ece_present else "ECE-negative")
    call_color = "#b91c1c" if ece_present else "#166534"

    rows = "".join(f"<tr><td>{l}</td><td>{v:,}</td><td>{ml}</td></tr>"
                   for l, v, ml in stats)
    stats_html = (f"<table><tr><th>Mask</th><th>Voxels</th><th>Volume (mL)"
                  f"</th></tr>{rows}</table>") if stats else ""

    body = "".join(f"<h2>{t}</h2>{c}" for t, c in sections)
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Meso-Regions report — patient {patient_id}</title>
<style>
 body {{ font-family: -apple-system, Segoe UI, sans-serif; max-width: 980px;
        margin: 2rem auto; color: #1f2937; padding: 0 1rem; }}
 img {{ max-width: 100%; }}
 table {{ border-collapse: collapse; }} td, th {{ border: 1px solid #d1d5db;
        padding: 4px 10px; text-align: right; }} th {{ background: #f3f4f6; }}
 .call {{ font-size: 1.15rem; font-weight: 600; color: {call_color}; }}
 .meta, .disclaimer {{ color: #6b7280; font-size: 0.85rem; }}
 .disclaimer {{ border: 1px solid #fbbf24; background: #fffbeb;
        padding: .6rem .8rem; border-radius: 6px; color: #92400e; }}
</style></head><body>
<h1>Meso-Regions — patient {patient_id}</h1>
<p class="meta">Method: {method or "n/a"} · reference {ref_t} s ·
generated {datetime.now():%Y-%m-%d %H:%M}</p>
<p class="disclaimer">{DISCLAIMER}</p>
<p class="call">{call}</p>
{stats_html}
{body}
</body></html>"""

    output_path = Path(output_path)
    output_path.write_text(html)
    return output_path
