"""Self-contained HTML patient report for Meso-Regions pipeline outputs.

Generates a single HTML file per patient with:
- static 3-plane overlays,
- an interactive slice viewer (slider / mouse-wheel) where ECE-positive
  regions are composited client-side from an embedded label map — clicking a
  region isolates it and its curve, and vice versa,
- per-superspel signal-intensity curves (clickable SVG) classified in place
  by the published ECE rule,
- the patient-level ECE call.

Everything (images, label maps, curve data) is base64/inline — no external
assets, no JS libraries, no data upload.
"""

import base64
import io
import json
from datetime import datetime
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import nibabel as nib
import numpy as np
import pandas as pd
from PIL import Image

DISCLAIMER = ("Research use only — this report is generated by research "
              "software and must not be used for clinical diagnosis or "
              "treatment decisions.")

PLANES = {"axial": 2, "coronal": 1, "sagittal": 0}
MAX_SCROLL_FRAMES = 72
_CMAP = plt.get_cmap("tab20")


# --------------------------------------------------------------------------
# shared helpers
# --------------------------------------------------------------------------

def region_color_map(mask_data):
    """Stable region-id -> RGB (0-1 floats): i-th smallest label = tab20(i)."""
    labels = sorted(int(l) for l in np.unique(mask_data) if l > 0)
    return {lab: _CMAP(i % 20)[:3] for i, lab in enumerate(labels)}


def _fig_to_b64(fig, dpi=130):
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode()


def _pil_to_b64(arr, mode):
    buf = io.BytesIO()
    Image.fromarray(arr, mode).save(buf, format="PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode()


def _pick_slice(mask_data, axis):
    axes = tuple(i for i in range(3) if i != axis)
    areas = mask_data.sum(axis=axes)
    return int(np.argmax(areas)) if areas.max() > 0 else mask_data.shape[axis] // 2


def _slice2d(data, axis, idx):
    sl = [slice(None)] * 3
    sl[axis] = idx
    return np.rot90(data[tuple(sl)])


def _is_ece_positive(t, y, ref_t):
    """Published ECE rule: minimum pre-contrast, peak at or before ref_t,
    monotonically rising before the peak and falling after."""
    y = np.asarray(y, dtype=float)
    if y.max() <= 0:
        return False
    peak = int(np.argmax(y))
    return (int(np.argmin(y)) == 0
            and t[peak] <= ref_t
            and np.all(np.diff(y[:peak + 1]) >= 0)
            and np.all(np.diff(y[peak:]) <= 0))


def _hex(rgb):
    return "#%02x%02x%02x" % tuple(int(round(c * 255)) for c in rgb)


# --------------------------------------------------------------------------
# static figures
# --------------------------------------------------------------------------

def _label_rgba(m, base_color=None, color_map=None, alpha=0.45):
    overlay = np.zeros((*m.shape, 4))
    if color_map:
        for lab, color in color_map.items():
            overlay[m == lab] = (*color, 0.75)
    elif base_color is not None:
        overlay[m > 0] = (*matplotlib.colors.to_rgb(base_color), alpha)
    return overlay


def _overlay_figure(image, layers):
    fig, axes = plt.subplots(1, 3, figsize=(12, 4.2))
    pick_from = list(layers.values())[-1][0] if layers else image
    for ax, (plane, axis) in zip(axes, PLANES.items()):
        idx = _pick_slice(pick_from, axis)
        ax.imshow(_slice2d(image, axis, idx), cmap="gray",
                  interpolation="nearest")
        for _, (data, color, color_map) in layers.items():
            m = _slice2d(data, axis, idx)
            ax.imshow(_label_rgba(m, color, color_map),
                      interpolation="nearest")
        ax.set_title(f"{plane} (slice {idx})", fontsize=10)
        ax.axis("off")
    handles = [plt.Line2D([0], [0], marker="s", linestyle="", color=c or "k",
                          label=(f"{l} (one color per region)" if cm else l))
               for l, (_, c, cm) in layers.items()]
    if handles:
        fig.legend(handles=handles, loc="lower center", ncol=len(handles),
                   frameon=False, fontsize=9)
    return _fig_to_b64(fig)


def _curves_figure(curves_df, ref_t, color_map=None):
    """Static PNG fallback used when there is no ECE label map to link to."""
    fig, ax = plt.subplots(figsize=(8, 4.5))
    t = [float(c) for c in curves_df.columns]
    n_ece = 0
    for i, (_, row) in enumerate(curves_df.iterrows()):
        if _is_ece_positive(t, row.values, ref_t):
            color = (color_map or {}).get(i, "crimson")
            ax.plot(t, row.values, color=color, lw=1.6, zorder=2)
            ax.annotate(str(i), (t[-1], row.values[-1]),
                        xytext=(4, 0), textcoords="offset points",
                        color=color, fontsize=7, va="center")
            n_ece += 1
        else:
            ax.plot(t, row.values, color="0.75", lw=0.8, zorder=1)
    ax.axvline(ref_t, color="0.4", ls="--", lw=1,
               label=f"{ref_t} s reference")
    ax.plot([], [], color="0.75", label=f"superspels (n={len(curves_df)})")
    ax.plot([], [], color="0.2", label=f"satisfy ECE rule (n={n_ece})")
    ax.set_xlabel("Time post-contrast (s)")
    ax.set_ylabel("Mean signal intensity")
    ax.legend(frameon=False, fontsize=9)
    ax.spines[["top", "right"]].set_visible(False)
    return _fig_to_b64(fig), n_ece


# --------------------------------------------------------------------------
# interactive linked viewer (canvas slice viewer + clickable SVG curves)
# --------------------------------------------------------------------------

def _window_u8(image):
    lo, hi = np.percentile(image, [2, 98])
    g = np.clip((image - lo) / max(hi - lo, 1e-6), 0, 1)
    return (g * 255).astype(np.uint8)


def _bg_frame(image_u8, context_layers, axis, idx):
    """Grayscale slice with non-interactive layers baked in, as base64 PNG."""
    g = _slice2d(image_u8, axis, idx)
    rgb = np.stack([g] * 3, axis=-1).astype(float)
    for data, color in context_layers:
        m = _slice2d(data, axis, idx) > 0
        c = np.array(matplotlib.colors.to_rgb(color)) * 255
        rgb[m] = rgb[m] * 0.55 + c * 0.45
    return _pil_to_b64(rgb.astype(np.uint8), "RGB")


def _label_frame(ece_data, axis, idx):
    """ECE label slice encoded as RGB PNG (R = id & 255, G = id >> 8)."""
    m = _slice2d(ece_data, axis, idx).astype(np.int32)
    rgb = np.zeros((*m.shape, 3), dtype=np.uint8)
    rgb[..., 0] = m & 255
    rgb[..., 1] = m >> 8
    return _pil_to_b64(rgb, "RGB")


def _curves_svg(curves_df, ref_t, color_map):
    """Inline SVG curve chart; ECE-positive curves are clickable polylines
    carrying data-region ids matching the label map."""
    W, H, padL, padR, padT, padB = 780, 430, 58, 34, 16, 42
    t = [float(c) for c in curves_df.columns]
    ys = curves_df.values.astype(float)
    ymin, ymax = float(ys.min()), float(ys.max())
    span = max(ymax - ymin, 1e-6)
    ymin -= span * 0.04
    ymax += span * 0.04

    def X(x):
        return padL + (x - t[0]) / (t[-1] - t[0]) * (W - padL - padR)

    def Y(y):
        return H - padB - (y - ymin) / (ymax - ymin) * (H - padB - padT)

    parts = [f'<svg id="curves" viewBox="0 0 {W} {H}" '
             f'xmlns="http://www.w3.org/2000/svg">']
    # axes + ticks
    parts.append(f'<line x1="{padL}" y1="{H - padB}" x2="{W - padR}" '
                 f'y2="{H - padB}" stroke="#9ca3af"/>')
    parts.append(f'<line x1="{padL}" y1="{padT}" x2="{padL}" '
                 f'y2="{H - padB}" stroke="#9ca3af"/>')
    for x in t:
        parts.append(f'<text x="{X(x):.0f}" y="{H - padB + 16}" '
                     f'text-anchor="middle" class="tick">{x:.0f}</text>')
    for yv in np.linspace(ymin, ymax, 5):
        parts.append(f'<text x="{padL - 6}" y="{Y(yv) + 3:.0f}" '
                     f'text-anchor="end" class="tick">{yv:.0f}</text>')
    parts.append(f'<text x="{(padL + W - padR) / 2:.0f}" y="{H - 6}" '
                 f'text-anchor="middle" class="tick">Time post-contrast '
                 f'(s)</text>')
    # reference line
    parts.append(f'<line x1="{X(ref_t):.1f}" y1="{padT}" x2="{X(ref_t):.1f}" '
                 f'y2="{H - padB}" stroke="#9ca3af" stroke-dasharray="5,4"/>')

    n_ece = 0
    ece_parts = []
    for i, row in enumerate(ys):
        pts = " ".join(f"{X(a):.1f},{Y(b):.1f}" for a, b in zip(t, row))
        if _is_ece_positive(t, row, ref_t) and i in color_map:
            n_ece += 1
            c = _hex(color_map[i])
            ece_parts.append(
                f'<g class="ece" data-region="{i}">'
                f'<polyline points="{pts}" fill="none" stroke="{c}" '
                f'stroke-width="2.2"/>'
                f'<text x="{X(t[-1]) + 5:.1f}" y="{Y(row[-1]) + 3:.1f}" '
                f'fill="{c}" class="rlab">{i}</text></g>')
        else:
            parts.append(f'<polyline points="{pts}" fill="none" '
                         f'stroke="#d1d5db" stroke-width="1"/>')
    parts.extend(ece_parts)   # positives drawn on top
    parts.append("</svg>")
    return "".join(parts), n_ece


def _interactive_section(image, layers, ece_color_map, curves_df, ref_t,
                         plane):
    """Linked slice viewer + curves: click a region to isolate its curve,
    click a curve to isolate its region."""
    axis = PLANES[plane]
    image_u8 = _window_u8(image)
    ece_data = layers["ECE-positive regions"][0].astype(np.int32)
    context_layers = [(d, c) for l, (d, c, cm) in layers.items()
                      if cm is None]

    union = ece_data > 0
    for d, _ in context_layers:
        union |= d > 0
    present = np.where(union.sum(axis=tuple(i for i in range(3)
                                            if i != axis)) > 0)[0]
    lo = max(int(present.min()) - 2, 0) if len(present) else 0
    hi = (min(int(present.max()) + 2, image.shape[axis] - 1)
          if len(present) else image.shape[axis] - 1)
    idxs = list(range(lo, hi + 1))
    if len(idxs) > MAX_SCROLL_FRAMES:
        idxs = idxs[::int(np.ceil(len(idxs) / MAX_SCROLL_FRAMES))]

    bgs = [_bg_frame(image_u8, context_layers, axis, i) for i in idxs]
    labs = [_label_frame(ece_data, axis, i) for i in idxs]

    svg, n_ece = _curves_svg(curves_df, ref_t, ece_color_map)
    palette = {int(k): [int(round(c * 255)) for c in v]
               for k, v in ece_color_map.items()}
    start = len(idxs) // 2

    return f"""
<p class="meta">Click an ECE region in the image to isolate its curve — or
click a curve to isolate its region. Click again (or press Esc) to reset.
Drag the slider or use the mouse wheel to change slice.</p>
<div class="viewer">
 <div class="vleft">
  <canvas id="cv"></canvas>
  <div class="scrollbar">
   <input type="range" id="rng" min="0" max="{len(idxs) - 1}" value="{start}"
          style="width:100%">
   <span class="meta">{plane} slice <span id="slab"></span> ·
     <span id="sel">all regions</span></span>
  </div>
 </div>
 <div class="vright">{svg}</div>
</div>
<script>
const BGS=[{",".join(f'"{b}"' for b in bgs)}];
const LABS=[{",".join(f'"{l}"' for l in labs)}];
const IDX=[{",".join(str(i) for i in idxs)}];
const PAL={json.dumps(palette)};
let cur={start}, selected=0;
const cv=document.getElementById("cv"), ctx=cv.getContext("2d");
const off=document.createElement("canvas"), octx=off.getContext("2d");
const rng=document.getElementById("rng"),
      slab=document.getElementById("slab"),
      sel=document.getElementById("sel");
function draw(){{
  const bg=new Image();
  bg.onload=()=>{{
    cv.width=bg.width; cv.height=bg.height;
    ctx.imageSmoothingEnabled=false;
    ctx.drawImage(bg,0,0);
    const lb=new Image();
    lb.onload=()=>{{
      off.width=lb.width; off.height=lb.height;
      octx.drawImage(lb,0,0);
      const L=octx.getImageData(0,0,off.width,off.height);
      const O=ctx.getImageData(0,0,cv.width,cv.height);
      for(let i=0;i<L.data.length;i+=4){{
        const id=L.data[i]+L.data[i+1]*256;
        if(id>0&&(!selected||id===selected)){{
          const c=PAL[id]; if(c){{
            const a=0.75;
            O.data[i]=O.data[i]*(1-a)+c[0]*a;
            O.data[i+1]=O.data[i+1]*(1-a)+c[1]*a;
            O.data[i+2]=O.data[i+2]*(1-a)+c[2]*a;
          }}
        }}
      }}
      ctx.putImageData(O,0,0);
    }};
    lb.src="data:image/png;base64,"+LABS[cur];
  }};
  bg.src="data:image/png;base64,"+BGS[cur];
  slab.textContent=IDX[cur];
}}
function setSel(id){{
  selected=(selected===id)?0:id;
  sel.textContent=selected?("region "+selected):"all regions";
  document.querySelectorAll("#curves .ece").forEach(g=>{{
    g.classList.toggle("dim",
      selected!==0 && +g.dataset.region!==selected);
  }});
  draw();
}}
rng.addEventListener("input",e=>{{cur=+e.target.value;draw();}});
cv.addEventListener("wheel",e=>{{e.preventDefault();
  cur=Math.min(Math.max(cur+(e.deltaY>0?1:-1),0),BGS.length-1);
  rng.value=cur;draw();}},{{passive:false}});
cv.addEventListener("click",e=>{{
  const r=cv.getBoundingClientRect();
  const x=Math.floor((e.clientX-r.left)*cv.width/r.width);
  const y=Math.floor((e.clientY-r.top)*cv.height/r.height);
  const p=octx.getImageData(x,y,1,1).data;
  const id=p[0]+p[1]*256;
  if(id>0&&PAL[id]) setSel(id);
}});
document.querySelectorAll("#curves .ece").forEach(g=>{{
  g.style.cursor="pointer";
  g.addEventListener("click",()=>setSel(+g.dataset.region));
}});
document.addEventListener("keydown",e=>{{
  if(e.key==="Escape"&&selected) setSel(selected);}});
draw();
</script>""", n_ece


# --------------------------------------------------------------------------
# report assembly
# --------------------------------------------------------------------------

def generate_report(image_path, output_path, patient_id="unknown",
                    ece_mask_path=None, fluid_mask_path=None,
                    pleural_mask_path=None, supervoxels_path=None,
                    curves_csv=None, ece_curves_csv=None, ref_t=270,
                    method="", scroll_plane="coronal", no_scroll=False):
    """Build the HTML report; returns the output path."""
    img_nii = nib.load(str(image_path))
    image = np.asanyarray(img_nii.dataobj).astype(float)
    if image.ndim > 3:
        image = image[..., 0]
    voxel_mm3 = float(abs(np.linalg.det(img_nii.affine[:3, :3])))

    # label: (data, single_color, color_map) — only ECE gets per-region colors
    layers, stats, ece_color_map = {}, [], None
    for label, path, color in [
            ("pleural fluid", fluid_mask_path, "gold"),
            ("pleural region", pleural_mask_path, "darkorange"),
            ("supervoxels", supervoxels_path, "steelblue"),
            ("ECE-positive regions", ece_mask_path, "crimson")]:
        if path:
            data = np.asanyarray(nib.load(str(path)).dataobj)
            color_map = None
            if label == "ECE-positive regions":
                ece_color_map = color_map = region_color_map(data)
            layers[label] = (data, color, color_map)
            n_regions = len(np.unique(data)) - 1
            stats.append((label, n_regions,
                          round((data > 0).sum() * voxel_mm3 / 1000, 1)))

    if ece_curves_csv and not curves_csv:
        curves_csv = ece_curves_csv
    curves = pd.read_csv(curves_csv) if curves_csv else None

    sections, n_ece = [], None
    if layers:
        sections.append(("Overlays",
                         f'<img src="data:image/png;base64,'
                         f'{_overlay_figure(image, layers)}"/>'))

    interactive = (ece_color_map and curves is not None and not no_scroll)
    if interactive:
        html_block, n_ece = _interactive_section(
            image, layers, ece_color_map, curves, ref_t, scroll_plane)
        sections.append(("Linked slice viewer and curves", html_block))
    else:
        if curves is not None:
            b64, n_ece = _curves_figure(curves, ref_t, ece_color_map)
            sections.append(("Signal-intensity curves",
                             f'<img src="data:image/png;base64,{b64}"/>'))

    ece_layer = layers.get("ECE-positive regions")
    ece_present = (n_ece or 0) > 0 or (
        ece_layer is not None and (ece_layer[0] > 0).sum() > 0)
    call = ("ECE-POSITIVE — malignancy suspected by the automated rule"
            if ece_present else "ECE-negative")
    call_color = "#b91c1c" if ece_present else "#166534"

    rows = "".join(f"<tr><td>{l}</td><td>{n:,}</td><td>{ml}</td></tr>"
                   for l, n, ml in stats)
    stats_html = (f"<table><tr><th>Layer</th><th>Regions</th><th>Volume (mL)"
                  f"</th></tr>{rows}</table>") if stats else ""

    body = "".join(f"<h2>{t}</h2>{c}" for t, c in sections)
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Meso-Regions report — patient {patient_id}</title>
<style>
 body {{ font-family: -apple-system, Segoe UI, sans-serif; max-width: 1080px;
        margin: 2rem auto; color: #1f2937; padding: 0 1rem; }}
 img {{ max-width: 100%; }}
 .viewer {{ display: flex; gap: 1rem; flex-wrap: wrap; align-items: flex-start; }}
 .vleft {{ flex: 1 1 320px; }} .vright {{ flex: 1 1 420px; }}
 .vright svg {{ width: 100%; height: auto; }}
 #cv {{ width: 100%; image-rendering: pixelated; cursor: crosshair; }}
 .scrollbar {{ margin: .4rem auto; text-align: center; }}
 .tick {{ font-size: 11px; fill: #6b7280; }}
 .rlab {{ font-size: 11px; font-weight: 600; }}
 .ece.dim {{ opacity: 0.12; }}
 table {{ border-collapse: collapse; }} td, th {{ border: 1px solid #d1d5db;
        padding: 4px 10px; text-align: right; }} th {{ background: #f3f4f6; }}
 .call {{ font-size: 1.15rem; font-weight: 600; color: {call_color}; }}
 .meta, .disclaimer {{ color: #6b7280; font-size: 0.85rem; }}
 .disclaimer {{ border: 1px solid #fbbf24; background: #fffbeb;
        padding: .6rem .8rem; border-radius: 6px; color: #92400e; }}
</style></head><body>
<h1>Meso-Regions — patient {patient_id}</h1>
<p class="meta">Method: {method or "n/a"} · reference {ref_t} s ·
generated {datetime.now():%Y-%m-%d %H:%M}</p>
<p class="disclaimer">{DISCLAIMER}</p>
<p class="call">{call}</p>
{stats_html}
{body}
</body></html>"""

    output_path = Path(output_path)
    output_path.write_text(html)
    return output_path
