"""Self-contained HTML patient report for Meso-Regions pipeline outputs.

Generates a single HTML file per patient with slice overlays (reference MRI +
fluid / pleural-region / supervoxel / ECE layers), a lightweight slice slider,
per-superspel signal-intensity curves, and the patient-level ECE call.
Label-map masks (integer region ids) are rendered with one color per region.
All images are embedded as base64 — no external assets, no data upload.
"""

import base64
import io
from datetime import datetime
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import nibabel as nib
import numpy as np
import pandas as pd

DISCLAIMER = ("Research use only — this report is generated by research "
              "software and must not be used for clinical diagnosis or "
              "treatment decisions.")

PLANES = {"axial": 2, "coronal": 1, "sagittal": 0}
MAX_SCROLL_FRAMES = 72
_CMAP = plt.get_cmap("tab20")


def _fig_to_b64(fig, dpi=130):
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode()


def _pick_slice(mask_data, axis):
    axes = tuple(i for i in range(3) if i != axis)
    areas = mask_data.sum(axis=axes)
    return int(np.argmax(areas)) if areas.max() > 0 else mask_data.shape[axis] // 2


def _slice2d(data, axis, idx):
    sl = [slice(None)] * 3
    sl[axis] = idx
    return np.rot90(data[tuple(sl)])


def _label_rgba(m, base_color=None, alpha=0.45):
    """RGBA overlay for a 2D mask slice. Integer label maps get one color per
    region id (stable across slices); binary masks get `base_color`."""
    overlay = np.zeros((*m.shape, 4))
    labels = np.unique(m)
    labels = labels[labels > 0]
    if base_color is not None and (len(labels) <= 1 or m.max() == 1):
        overlay[m > 0] = (*matplotlib.colors.to_rgb(base_color), alpha)
        return overlay
    for lab in labels:
        color = _CMAP(int(lab) % 20)[:3]
        overlay[m == lab] = (*color, alpha)
    return overlay


def _render_slice(image, layers, axis, idx, figsize=(4.6, 4.6), dpi=95):
    fig, ax = plt.subplots(figsize=figsize)
    ax.imshow(_slice2d(image, axis, idx), cmap="gray",
              interpolation="nearest")
    for _, (data, color, per_region) in layers.items():
        m = _slice2d(data, axis, idx)
        ax.imshow(_label_rgba(m, None if per_region else color),
                  interpolation="nearest")
    ax.axis("off")
    return _fig_to_b64(fig, dpi=dpi)


def _overlay_figure(image, layers):
    fig, axes = plt.subplots(1, 3, figsize=(12, 4.2))
    pick_from = list(layers.values())[-1][0] if layers else image
    for ax, (plane, axis) in zip(axes, PLANES.items()):
        idx = _pick_slice(pick_from, axis)
        ax.imshow(_slice2d(image, axis, idx), cmap="gray",
                  interpolation="nearest")
        for _, (data, color, per_region) in layers.items():
            m = _slice2d(data, axis, idx)
            ax.imshow(_label_rgba(m, None if per_region else color),
                      interpolation="nearest")
        ax.set_title(f"{plane} (slice {idx})", fontsize=10)
        ax.axis("off")
    handles = [plt.Line2D([0], [0], marker="s", linestyle="", color=c or "k",
                          label=(f"{l} (per-region colors)" if pr else l))
               for l, (_, c, pr) in layers.items()]
    if handles:
        fig.legend(handles=handles, loc="lower center", ncol=len(handles),
                   frameon=False, fontsize=9)
    return _fig_to_b64(fig)


def _scroll_section(image, layers, plane="coronal"):
    """Pre-rendered slice stack + a vanilla-JS range slider."""
    axis = PLANES[plane]
    if layers:
        union = np.zeros(image.shape[:3], dtype=bool)
        for data, _, _ in layers.values():
            union |= data > 0
        present = np.where(union.sum(axis=tuple(i for i in range(3)
                                                if i != axis)) > 0)[0]
        lo = max(int(present.min()) - 2, 0)
        hi = min(int(present.max()) + 2, image.shape[axis] - 1)
    else:
        lo, hi = 0, image.shape[axis] - 1
    idxs = list(range(lo, hi + 1))
    if len(idxs) > MAX_SCROLL_FRAMES:
        stride = int(np.ceil(len(idxs) / MAX_SCROLL_FRAMES))
        idxs = idxs[::stride]

    frames = [_render_slice(image, layers, axis, i) for i in idxs]
    frames_js = ",".join(f'"{f}"' for f in frames)
    labels_js = ",".join(str(i) for i in idxs)
    start = len(idxs) // 2
    return f"""
<div class="scroll">
 <img id="scrollImg" src="data:image/png;base64,{frames[start]}"/>
 <div class="scrollbar">
  <input type="range" id="scrollRange" min="0" max="{len(idxs) - 1}"
         value="{start}" style="width:100%">
  <span class="meta">{plane} slice <span id="scrollLabel"></span></span>
 </div>
</div>
<script>
 const frames=[{frames_js}], labels=[{labels_js}];
 const img=document.getElementById("scrollImg"),
       rng=document.getElementById("scrollRange"),
       lab=document.getElementById("scrollLabel");
 function show(i){{ img.src="data:image/png;base64,"+frames[i];
                    lab.textContent=labels[i]; }}
 rng.addEventListener("input",e=>show(+e.target.value));
 img.addEventListener("wheel",e=>{{ e.preventDefault();
   rng.value=Math.min(Math.max(+rng.value+(e.deltaY>0?1:-1),0),
                      frames.length-1); show(+rng.value); }});
 show({start});
</script>"""


def _is_ece_positive(t, y, ref_t):
    """Published ECE rule: minimum pre-contrast, peak at or before ref_t,
    monotonically rising before the peak and falling after."""
    y = np.asarray(y, dtype=float)
    if y.max() <= 0:
        return False
    peak = int(np.argmax(y))
    return (int(np.argmin(y)) == 0
            and t[peak] <= ref_t
            and np.all(np.diff(y[:peak + 1]) >= 0)
            and np.all(np.diff(y[peak:]) <= 0))


def _curves_figure(curves_df, ref_t):
    fig, ax = plt.subplots(figsize=(8, 4.5))
    t = [float(c) for c in curves_df.columns]
    n_ece = 0
    for _, row in curves_df.iterrows():
        if _is_ece_positive(t, row.values, ref_t):
            ax.plot(t, row.values, color="crimson", lw=1.4, zorder=2)
            n_ece += 1
        else:
            ax.plot(t, row.values, color="0.75", lw=0.8, zorder=1)
    ax.axvline(ref_t, color="0.4", ls="--", lw=1,
               label=f"{ref_t} s reference")
    ax.plot([], [], color="0.75", label=f"superspels (n={len(curves_df)})")
    ax.plot([], [], color="crimson",
            label=f"satisfy ECE rule (n={n_ece})")
    ax.set_xlabel("Time post-contrast (s)")
    ax.set_ylabel("Mean signal intensity")
    ax.legend(frameon=False, fontsize=9)
    ax.spines[["top", "right"]].set_visible(False)
    return _fig_to_b64(fig), n_ece


def generate_report(image_path, output_path, patient_id="unknown",
                    ece_mask_path=None, fluid_mask_path=None,
                    pleural_mask_path=None, supervoxels_path=None,
                    curves_csv=None, ece_curves_csv=None, ref_t=270,
                    method="", scroll_plane="coronal", no_scroll=False):
    """Build the HTML report; returns the output path."""
    img_nii = nib.load(str(image_path))
    image = np.asanyarray(img_nii.dataobj).astype(float)
    if image.ndim > 3:
        image = image[..., 0]
    voxel_mm3 = float(abs(np.linalg.det(img_nii.affine[:3, :3])))

    # label: (data, single_color or None, per_region_colors)
    layers, stats = {}, []
    for label, path, color, per_region in [
            ("pleural fluid", fluid_mask_path, "gold", False),
            ("pleural region", pleural_mask_path, "darkorange", False),
            ("supervoxels", supervoxels_path, None, True),
            ("ECE-positive regions", ece_mask_path, "crimson", True)]:
        if path:
            data = np.asanyarray(nib.load(str(path)).dataobj)
            layers[label] = (data, color, per_region)
            n_regions = len(np.unique(data)) - 1
            stats.append((label, n_regions,
                          round((data > 0).sum() * voxel_mm3 / 1000, 1)))

    sections = []
    if layers:
        sections.append(("Overlays",
                         f'<img src="data:image/png;base64,'
                         f'{_overlay_figure(image, layers)}"/>'))
        if not no_scroll:
            sections.append((f"Slice viewer ({scroll_plane})",
                             _scroll_section(image, layers, scroll_plane)))

    n_ece = None
    if ece_curves_csv and not curves_csv:
        curves_csv = ece_curves_csv
    if curves_csv:
        curves = pd.read_csv(curves_csv)
        b64, n_ece = _curves_figure(curves, ref_t)
        sections.append(("Signal-intensity curves",
                         f'<img src="data:image/png;base64,{b64}"/>'))

    ece_layer = layers.get("ECE-positive regions")
    ece_present = (n_ece or 0) > 0 or (
        ece_layer is not None and (ece_layer[0] > 0).sum() > 0)
    call = ("ECE-POSITIVE — malignancy suspected by the automated rule"
            if ece_present else "ECE-negative")
    call_color = "#b91c1c" if ece_present else "#166534"

    rows = "".join(f"<tr><td>{l}</td><td>{n:,}</td><td>{ml}</td></tr>"
                   for l, n, ml in stats)
    stats_html = (f"<table><tr><th>Layer</th><th>Regions</th><th>Volume (mL)"
                  f"</th></tr>{rows}</table>") if stats else ""

    body = "".join(f"<h2>{t}</h2>{c}" for t, c in sections)
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Meso-Regions report — patient {patient_id}</title>
<style>
 body {{ font-family: -apple-system, Segoe UI, sans-serif; max-width: 980px;
        margin: 2rem auto; color: #1f2937; padding: 0 1rem; }}
 img {{ max-width: 100%; }}
 .scroll img {{ display: block; margin: 0 auto; max-height: 560px; }}
 .scrollbar {{ max-width: 480px; margin: .4rem auto; text-align: center; }}
 table {{ border-collapse: collapse; }} td, th {{ border: 1px solid #d1d5db;
        padding: 4px 10px; text-align: right; }} th {{ background: #f3f4f6; }}
 .call {{ font-size: 1.15rem; font-weight: 600; color: {call_color}; }}
 .meta, .disclaimer {{ color: #6b7280; font-size: 0.85rem; }}
 .disclaimer {{ border: 1px solid #fbbf24; background: #fffbeb;
        padding: .6rem .8rem; border-radius: 6px; color: #92400e; }}
</style></head><body>
<h1>Meso-Regions — patient {patient_id}</h1>
<p class="meta">Method: {method or "n/a"} · reference {ref_t} s ·
generated {datetime.now():%Y-%m-%d %H:%M}</p>
<p class="disclaimer">{DISCLAIMER}</p>
<p class="call">{call}</p>
{stats_html}
{body}
</body></html>"""

    output_path = Path(output_path)
    output_path.write_text(html)
    return output_path
